# Generated by Django 5.1.4 on 2024-12-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pic/'),
        ),
    ]
