# Generated by Django 5.1.4 on 2024-12-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default_profile_pic.jpeg', null=True, upload_to='profile_pic/'),
        ),
    ]
